---
name: s3 to sitemap

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # every day at 4am UTC

jobs:
  s3-to-sitemap:
    name: s3-to-sitemap
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run ckan-sitemap
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task catalog-gather
            --command "ckan geodatagov sitemap-to-s3"
            --name sitemap
            -m 3G -k 3G
          cf_org: gsa-datagov
          cf_space: prod
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
      # TODO remove tmate option
      - name: Setup tmate session on fail
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
